---
name: tests

on:
  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - README.md

  pull_request:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - README.md

jobs:
  tests:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package [pip]
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install -e .[dev]
    - name: Style check [isort]
      run: isort . --check
    - name: Style check [black]
      run: black . --check
    - name: Style check [flake8]
      run: flake8 .
    - name: Type check [mypy]
      run: mypy .
    - name: Unit tests [pytest]
      run: pytest
