---
name: tests

on:
  push:
    branches: [ main, ci-* ]
    paths-ignore:
    - .gitignore
    - README.md

  pull_request:
    branches: [ main ]
    paths-ignore:
    - .gitignore
    - README.md

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout euler
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load venv cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ hashFiles('**/poetry.lock') }}
    - name: Install euler
      run: poetry install --no-interaction

    - name: isort
      run: poetry run isort . --check
    - name: black
      run: poetry run black . --check
    - name: flake8
      run: poetry run flake8 .
    - name: mypy
      run: poetry run mypy .
    - name: pytest
      run: poetry run pytest --cov-report=xml --cov=./

    - name: Upload codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
